### ISSUE TITLE
Remove COMLibrary struct

### ISSUE THREAD

**Issue by surban** [ohadravid/wmi-rs#21]
The `COMLibrary` struct initializes COM when constructed and de-initializes it when dropped. This is fine in a simple application where `wmi-rs` is the only user of COM. However it causes problems when `wmi-rs` is used together with other crates that make COM calls. One such issue is that [repeated initialization of COM fails](https://stackoverflow.com/questions/5662382/why-does-com-coinitializesecurity-fail-in-my-dll). Generally speaking COM initialization is the responsibility of the main application and not something that a library should do.

**Comment by ohadravid** [comment]
I think I would be fine with having an `unsafe fn with_initialized_com(namespace_path: Option<&str>)` for `WMIConnection` (and changing the field to `Option<Rc<COMLibrary>>`), since I agree that an application might want to initialize COM in a more elaborate way.

However I wouldn't want to remove `COMLibrary` completely since it's a very useful abstraction to managing the "lifetime" of the `CoInit/CoUninit` calls, preventing you from accidentally calling `CoUninit` while `WMIConnection` is alive.

**Comment by surban** [comment]
I agree that this is a reasonable solution.

Another possibility might be to move all WMI COM calls to a private thread since COM initialization (except for security) is thread-specific.
