### ISSUE TITLE
UB when mixing windows-rs and wmi-rs crates

### ISSUE THREAD

**Issue by roblabla** [ohadravid/wmi-rs#39]
Hello,

I have a bit of a problem with safe code using both windows-rs and wmi-rs causing an ACCESS_VIOLATION. Here's a reproducer: https://github.com/roblabla/reproducer-wmi-windows-rs, you may need to run it multiple before it triggers the access violation as it depends on a race condition between threads. Here's what happens:

- In one thread, I use windows-rs to do some calls to WinRT. 
- In another thread, I use the `WMI` crate to interact with the WMI. This enforces a call to `CoInitialize` (through the `COMLibrary::new` constructor), and will call `CoUninitialize` when the `WMIConnection` is dropped.

Here's the problem: When the `WMIConnection` gets dropped, it will also drop the `COMLibrary`, which will call `CoUninitialize`. Because no `CoInitialize` is currently active in the WinRT thread, all currently loaded COM DLLs will be unloaded, *including* whatever DLL was loaded by WinRT. So the thread running WinRT code will segfault because the code it's running gets unloaded.

Now, windows-rs *does* try to initialize its COM environment. Specifically, if `RoGetActivationFactory` returns a `CO_E_NOTINITIALIZED` error, it calls `CoIncrementMTAUsage`, and never decrements the counter after, ensuring that the COM subsystem stays initialized forever.

The problem is that this leads to a race condition with the thread doing WMI calls, e.g. in case of this sequence of event:

- WMI calls `CoInitialize`
- WinRT factory runs. COM is initialized, so it does *not* call `CoIncrementMTAUsage`
- WMI finishes its work, calls CoUninitialized. This will lead to WinRT dlls being unloaded
- WinRT is now running code that got unmapped -> ACCESS_VIOLATION, UB.

------

Now, this all looks like an error in windows-rs, but while raising the issue there, I was met with basically a WONTFIX: https://github.com/microsoft/windows-rs/issues/1169. So I'm now opening this issue because it looks like calling `CoUninitialize` in a rust environment is basically expected to be unsafe, thus breaking the `COMLibrary` abstraction.

**Comment by ohadravid** [comment]
Hi @roblabla!
Thanks for the detailed explanation.
I also read the linked thread, and I think that the `WMI` crate falls under [this](https://github.com/microsoft/windows-rs/issues/1169#issuecomment-925107412):

> Additional calls [after CoIncrementMTAUsage] to CoInitialize paired with CoUninitialize are fine (and sometimes necessary when an STA is required) because they will simply act as additional references to the COM runtime and not cause the reference count to hit zero and begin unloading DLLs.

Since calling `CoUninitialize` yourself is `unsafe`, we can't really consider all possible of "maybe safe" impls abstracting over the `unsafe` call.

I also don't think a crate should "force" you to initialize COM (and prevent you form uninitializing it).

What I can suggest, given what @riverar said

> Continue to spread the message: never call CoUninitialize

is to change `COMLibrary::new` to create a non-`CoUninitialize`-ing instance,
and add a `COMLibrary::scoped` which will call `CoUninitialize`, with a warning that this is probably not what you want.
